version: 0.2

env:
  parameter-store:
    LOGIN_PASSWORD: docker-password

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y ca-certificates curl gnupg lsb-release
      - mkdir -p /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  pre_build:
    commands:
      - echo Entered the pre-build-stage
      - docker login -u kaustubhmali -p $LOGIN_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker Image
      - docker build -t kaustubhmali/hello-world-build .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push kaustubhmali/hello-world-build
  
artifacts:
  files:
    - '**/*'
  base-directory: 'trucks'