version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
      - apt-get install -y unzip
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Simple Web App
      - mvn clean install
      - zip truck.zip target/trucks.war

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type:
  files:
    - src/main/webapp/index.jsp
    - src/main/webapp/WEB-INF/web.xml
    - target/trucks.war